export const Env = {
  URI_API_LOCAL: process.env.REACT_APP_URI_API_LOCAL,
  URI_API_MELI: process.env.REACT_APP_URI_API_MELI,
  LANG_DEFAULT: process.env.REACT_APP_LANG_DEFAULT,
  CODE_AUTH_PUBLIC_JWT: process.env.REACT_APP_CODE_AUTH_JWT,
};
